repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.2
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: ["--select", "I", "--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
      - id: mypy
        args: ["--config-file=pyproject.toml"]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest tests
        language: python
        pass_filenames: false
        always_run: true

