name: Python Code Quality
on: [push, pull_request]

jobs:
  lock-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup/instal-uv.yaml
      - run: uv lock --locked
  linting:
    runs-on: ubuntu-latest
    needs: [lock-file]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup/instal-uv.yaml
      - run: uvx ruff check .
